export const cards = [
  {
    id: 1,
    title: "Google",
    description: "Software Engineer 1",
    status: "Applied",
    subtitle: "Applied on 2025-05-20",
  },
  {
    id: 2,
    title: "Instagram",
    description: "Software Engineer 1",
    status: "Tasked",
    subtitle: "Tasked on 2025-05-20",
  },
  {
    id: 3,
    title: "Aramco",
    description: "Senior Software Engineer",
    status: "Interviewing",
    subtitle: "Interviewing on 2025-05-20",
  },
  {
    id: 4,
    title: "Amazon",
    description: "Software Engineer 1",
    status: "Offer",
    subtitle: "Offer on 2025-05-20",
  },
  {
    id: 5,
    title: "Apple",
    description: "Software Engineer 1",
    status: "Rejected",
    subtitle: "Rejected on 2025-05-20",
  },
  {
    id: 6,
    title: "Microsoft",
    description: "Software Engineer 1",
    status: "Rejected",
    subtitle: "Rejected on 2025-05-20",
  },
  {
    id: 7,
    title: "Facebook",
    description: "Software Engineer 1",
    status: "Applied",
    subtitle: "Applied on 2025-05-20",
  },
  {
    id: 8,
    title: "Twitter",
    description: "Software Engineer 1",
    status: "Interviewing",
    subtitle: "Interviewing on 2025-05-20",
  },
];
